### ISSUE TITLE
Add functional testing for services

### ISSUE THREAD

**Issue by danionescu0** [danionescu0/docker-flask-mongodb-example#20]

**Comment by danionescu0** [comment]
Maybe use this: https://www.patricksoftwareblog.com/testing-a-flask-application-using-pytest/

**Comment by neelabalan** [comment]
I have set up a folder in my plaground [repo](https://github.com/neelabalan/python-playground/tree/master/compose-mongodb) for understanding/experimenting functional tests and docker secrets. Once that goes well I will raise a PR in this repo.

**Comment by danionescu0** [comment]
Ok great.I'll work on #62

**Comment by neelabalan** [comment]
Hi. I've made some updates in my plaground [repo](https://github.com/neelabalan/python-playground/tree/master/compose-mongodb).
I've used pytest and this works good. Let me know what you think.

**Comment by danionescu0** [comment]
Ok, pytest it's great. I had in mind functional testing meaning to test the endpoints 
for example make a post request to users endpoint to create a user, and expect 200 OK
after that make a get request to see if our user it's there
make a delete request to delete a user
make a get request to see if the users dissapeared
etc

I'll make time tomorrow to make a test for one of the endpoints to show you my point of view. 

I'm not sure if your test it's functional or a unittest. A unit test is a test when the data is mocked (not touching databases, filesystems or making HTTP requests)

**Comment by neelabalan** [comment]
Hi. This functional test that I've implemented where actual data is stored in the DB (`testdb` in my example) after the request is made from user_test.py. I did a `docker-compose exec testdb sh` and verified that my POST, GET and DELETE request goes through and reflects what I have in DB. Although I have only the POST request (test) in my example which just creates a user and checks the `status_code` for 200, I wanted to make sure that this approach is okay with you before going any further.

**Comment by danionescu0** [comment]
I'm going to make a demo tomorrow and we'll discuss it ok?

**Comment by neelabalan** [comment]
ok

**Comment by danionescu0** [comment]
I've added some tests for, check my latest commit and tell me what do you think.

I've added a separate folder with the tests completly decouplet for the main project. I've used pytest, and added a utils.py file. Now it has just the database connection

The tests are isolated and i'm tesing just one api at a time

**Comment by neelabalan** [comment]
Yeah I get it. I was following the approach from 
https://flask.palletsprojects.com/en/1.1.x/testing/ 
and
https://blog.theodo.com/2015/07/functional-testing-in-an-environment-of-flask-micro-services/

I get what you are doing here with the explicit request calls and decoupling the tests from the main project (easier to test). I think I will go by your way for testing the services since I am not sure how good testing the way I did would suit the project structure and might require big changes.

I'll sync up the latest commit and start making PR from tomorrow. :+1:

**Comment by danionescu0** [comment]
Oh i see it now, i 've read (https://flask.palletsprojects.com/en/1.1.x/testing/) i think it is suitet for a single endpoint, and it runs the web server from withing the test.

Ok, would you like to write the all the test or will you like to write some of them ?

**Comment by neelabalan** [comment]
I would like to write all them.

**Comment by danionescu0** [comment]
Ok sure, i'll work on someting eles. Maybe the tic tac toe game

**Comment by neelabalan** [comment]
I am working on writing functional test for fulltext_search. I see that the index is created for the app_text and I am able to create multiple text for the same index
```
http://localhost:82/search/added


[
  {
    "text": "new text added",
    "date": "2021-03-11T06:51:04.482000"
  },
  {
    "text": "new text added",
    "date": "2021-03-11T06:51:06.545000"
  },
  {
    "text": "new text added",
    "date": "2021-03-11T06:50:57.962000"
  }
]
```

Am I doing something wrong here? My understanding is that it shouldn't add the same text again since app_text is the index

**Comment by danionescu0** [comment]
Fulltext search index is not an unique index, so you can add the same text many times

**Comment by neelabalan** [comment]
ok Thanks for the clarifying

**Comment by neelabalan** [comment]
I am looking at ways to modularize the pytest fixtures to avoid repetition. Didn't find anything promising yet. Let me know if you have any ideas/resources I look into.

**Comment by neelabalan** [comment]
I tried this but it didn't work (https://gist.github.com/peterhurford/09f7dcda0ab04b95c026c60fa49c2a68)

**Comment by danionescu0** [comment]
Ok, i'll try to find some solutions too today:)

**Comment by danionescu0** [comment]
Sorry i think i am to tired today i haven't found a way yet, it's more complicated than i suspected

**Comment by neelabalan** [comment]
meanwhile I will take look at other projects in github using pytest to get some idea

**Comment by danionescu0** [comment]
I've taken a look at this: https://medium.com/@yavinarba/pytest-fixtures-super-dry-tests-with-calleable-nested-fixtures-f8bcede38eb7

But my head hurts i can't understand how all of this works given a few hours of research.. sorry

**Comment by neelabalan** [comment]
I initially thought of using parametrize everywhere to pass the collection name but that once again looked repetitive and bad. I think this will need more time for good solution. I am going through the entire pytest documentation and couple of other libraries like https://github.com/ClearcodeHQ/pytest-mongo. It does look tricky :)

**Comment by danionescu0** [comment]
I did that too, created a conftest.py

import pytest
from utils import MongoDb
from pytest import FixtureRequest


@pytest.fixture
def collection(request: FixtureRequest):
    params = getattr(request, "param", None)
    print(params)
    con = MongoDb(host=params["host"])
    con.create_connection()
    con.set_collection(params["collection"])
    yield con
    con.drop()


and now the tests would it like this:

from conftest import collection


@pytest.mark.parametrize("collection", [{"host": "localhost", "collection": "baesian"}], indirect=True)
def test_upsert_item(collection):
    requests.post(url="{0}/item/{1}".format(baesian_host, item_id), data={"name": name})
    response = collection.get({})
    assert response[0]["name"] == name
    assert response[0]["nr_votes"] == 0

It is repetitive

**Comment by neelabalan** [comment]
yup exactly. This task is challenging and interesting.

**Comment by neelabalan** [comment]
We can do something like this. It is not the solution we expected but just a streamlined version of previous one

```python
# utils.py
class Collection:
    def __init__(self, client, collection):
        self.__client = client
        self.__collection = collection
    
    def upsert(self):
        pass

    def delete(self):
        pass

@pytest.fixture()
def client():
    con = MongoDb(host="localhost")
    con.create_connection()
    return con






# random.py
@pytest.fixture
def random():
    collection = Collection(client, "random")
    yield collection
    collection.drop()

```

What do you think?

**Comment by danionescu0** [comment]
It has less duplicated code, it's bit better why not

**Comment by neelabalan** [comment]
yeah. I combed the web for good solution and experimented with the code, Couldn't find anything good. Finally settled for something simple with less duplicated code. There is one more I could think of, We can use unittest and pytest together but didn't go ahead with that because this could bring more problem than it solves.

I will raise a PR for this tomorrow.

**Comment by danionescu0** [comment]
Ok great! Meanwhile I'll make a docker image for the game backend.

**Comment by neelabalan** [comment]
This is how it looks like
```python
# random.py
import pytest, requests
import datetime
from utils import Collection 

random_host = "http://localhost:800"

@pytest.fixture
def random_numbers(demo_db):
    collection = Collection(demo_db, "random_numbers")
    yield collection
    collection.drop()



# conftest.py
import pytest
from utils import MongoDb 

@pytest.fixture()
def demo_db():
    db = MongoDb(host="localhost")
    db.create_connection()
    return db.connection 




# utils.py
from pymongo import MongoClient, database


class MongoDb:
    def __init__(self, host="mongodb", dbname="demo") -> None:
        self.__host = host
        self.__dbname = dbname

    def create_connection(self):
        self.connection = MongoClient(self.__host, 27017)[self.__dbname]

class Collection:
    def __init__(self, db: database.Database, collection_name:str):
        self.__db = db
        self.__collection = collection_name 

    def get(self, query: dict, limit: int = 10, offset: int = 0):
        return list(
            self.__db[self.__collection].find(query).limit(limit).skip(offset)
        )

    def upsert(self, key, data: dict):
        self.__db[self.__collection].update_one(
            {"_id": key}, {"$set": data}, upsert=True
        )

    def delete(self, key):
        self.__db[self.__collection].delete_one({"_id": key})

    def delete_many(self, index, key):
        self.__db[self.__collection].delete_many({index: key})

    def drop(self):
        self.__db[self.__collection].drop()

```

Any suggestions?

**Comment by danionescu0** [comment]
In random.py I think you will need to import conftest.py right?

**Comment by neelabalan** [comment]
The tests have access to pytest fixture inside conftest without the import. I mirrored this approach from pytest doc.
https://docs.pytest.org/en/stable/fixture.html

**Comment by danionescu0** [comment]
Oh OK, raise a pr then it looks good

**Comment by neelabalan** [comment]
Hi. I am trying to add an image but the below code is not working. Couldn't figure out what I am doing wrong here.

```python
image = open(test_image_path, 'rb')
headers = {'Content-type': 'image/jpeg'}
resp = requests.put(url, headers=headers, files={'file': image} )
# File parameter not present!
```

**Comment by danionescu0** [comment]
I'll take a look today, and if i have a solution i'll push some code.

**Comment by danionescu0** [comment]
I've added test_photo.py, it ads a file

**Comment by neelabalan** [comment]
> I've added test_photo.py, it ads a file

I'll sync with the latest commit and try this.

**Comment by neelabalan** [comment]
Hi. I am having issue creating a book with put request. Can you help me with this.

```python
book = {
 'name': 'Intro to Computation and Programming using Python',
 'isbn': '9780262529624',
 'author': 'John Guttag',
 'publisher': 'MIT Press',
 'nr_available': 3
}
resp = requests.put('http://localhost:86/book/{}'.format(book['isbn']), data=book)
resp.status_code
# 500
```

```log
web-book-collection_1     | 172.18.0.1 - - [27/Mar/2021 05:50:24] "PUT /book/9780262529624 HTTP/1.1" 500 -
web-book-collection_1     | Traceback (most recent call last):
web-book-collection_1     |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
web-book-collection_1     |     return self.wsgi_app(environ, start_response)
web-book-collection_1     |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
web-book-collection_1     |     response = self.handle_exception(e)
web-book-collection_1     |   File "/usr/local/lib/python3.8/site-packages/flask_restplus/api.py", line 584, in error_router
web-book-collection_1     |     return original_handler(e)
web-book-collection_1     |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
web-book-collection_1     |     reraise(exc_type, exc_value, tb)
web-book-collection_1     |   File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 38, in reraise
web-book-collection_1     |     raise value.with_traceback(tb)
web-book-collection_1     |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
web-book-collection_1     |     response = self.full_dispatch_request()
web-book-collection_1     |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
web-book-collection_1     |     rv = self.handle_user_exception(e)
web-book-collection_1     |   File "/usr/local/lib/python3.8/site-packages/flask_restplus/api.py", line 584, in error_router
web-book-collection_1     |     return original_handler(e)
web-book-collection_1     |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
web-book-collection_1     |     reraise(exc_type, exc_value, tb)
web-book-collection_1     |   File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 38, in reraise
web-book-collection_1     |     raise value.with_traceback(tb)
web-book-collection_1     |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
web-book-collection_1     |     rv = self.dispatch_request()
web-book-collection_1     |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
web-book-collection_1     |     return self.view_functions[rule.endpoint](**req.view_args)
web-book-collection_1     |   File "/usr/local/lib/python3.8/site-packages/flask_restplus/api.py", line 325, in wrapper
web-book-collection_1     |     resp = resource(*args, **kwargs)
web-book-collection_1     |   File "/usr/local/lib/python3.8/site-packages/flask/views.py", line 89, in view
web-book-collection_1     |     return self.dispatch_request(*args, **kwargs)
web-book-collection_1     |   File "/usr/local/lib/python3.8/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
web-book-collection_1     |     resp = meth(*args, **kwargs)
web-book-collection_1     |   File "/root/flask-mongodb-example/python/bookcollection.py", line 191, in put
web-book-collection_1     |     book_api.payload['isbn'] = isbn
```

**Comment by neelabalan** [comment]
I am also tried a PUT request to user service (fastapi), GET request works fine
```python
resp = requests.put('http://localhost:88/users/104', data = {"name": "foo", "email": "email@email.com" })

resp.status_code
# 422

resp.text
# '{"detail":[{"loc":["body",0],"msg":"Expecting value: line 1 column 1 (char 0)","type":"value_error.jsondecode","ctx":{"msg":"Expecting value","doc":"name=foo&email=email%40email.com","pos":0,"lineno":1,"colno":1}}]}'
```

**Comment by danionescu0** [comment]
Sure I'll help, but I'm don't know if I have time today,  tomorrow I will for sure.

**Comment by danionescu0** [comment]
Your your put request looks fine

**Comment by neelabalan** [comment]
which one?

**Comment by danionescu0** [comment]
Put on book resource

**Comment by neelabalan** [comment]
I restarted docker compose. The same error pops up.

**Comment by danionescu0** [comment]
I've added a working demo of test_bookcollection with a put method? Tell me if it's working  on your system too ?

**Comment by neelabalan** [comment]
This works. I missed the headers argument and the json dumps part.

**Comment by neelabalan** [comment]
I noticed that in users-fastapi.py file the PUT request is used to create the user and POST is used to update it. I think it should be other way around.

**Comment by danionescu0** [comment]
Yes that is not correct, if you'll make that change in the code  could you please update the tests and Readme also?

**Comment by neelabalan** [comment]
sure

**Comment by danionescu0** [comment]
Done, thanks @neelabalan
