### ISSUE TITLE
getting error running `docker-compose build`

### ISSUE THREAD

**Issue by neelabalan** [danionescu0/docker-flask-mongodb-example#49]
I followed the instructions to start the micorservice and got the following error
```bash
~ docker-compose --version
docker-compose version 1.28.4, build cabd5cfb

~ docker --version
Docker version 20.10.2, build 2291f61

~ docker-compose build
WARNING: Some services (krakend) use the 'configs' key, which will be ignored. Compose does not support 'configs' configuration - use `docker stack deploy` to deploy to a swarm.
ERROR: Invalid restart policy "always"
```

I did some search in the internet for similar issues and found [this](https://github.com/docker/compose/issues/5110)
and made some changes to `docker-compose.yml` but I am not sure if this right way to do this.
```diff
     krakend:
         image: devopsfaith/krakend
         volumes:
-            - ./:/etc/krakend/
-        configs:
-          - krakend_config
+            - ./kraken.json:/etc/krakend
         ports:
             - "8080:8080"
```

Also I have the changed `deploy.restart_policy` to `on-failiure` since `always` option is not [available](https://docs.docker.com/compose/compose-file/compose-file-v3/). After making these changes I am able to locally start all the services.

Let me know if there is any further iteration on the above solution to raise a PR.

**Comment by danionescu0** [comment]
I've removed the restart policy yesterday because it was only in swarm. I've also removed the config section for krakend. Your solution with mounting just the kraken.json is better so please raise a PR  with that line and i'll test and approve it.

Thanks

**Comment by neelabalan** [comment]
Hi. I have raised a PR for the suggested change. Thanks.
