### ISSUE TITLE
Use Dash framework to plot a live graph

### ISSUE THREAD

**Issue by danionescu0** [danionescu0/docker-flask-mongodb-example#93]
A live graph may be usable for plotting mqtt sensor data

https://github.com/plotly/dash/

**Comment by neelabalan** [comment]
Hi. I've worked on this before. Is it possible to have live graph plotting with dash?
I had to refresh the browser everytime to get the latest data.

**Comment by danionescu0** [comment]
Hello
I found something in the documentation, which might be use for "live" data: https://dash.plotly.com/live-updates

**Comment by neelabalan** [comment]
Hi. I tried the sample code from the link you have shared and I noticed that the browser title bar has this nagging "updating..." everytime an update was made. I came across this issue in their repo and they seem to have put an update for this in `dash==1.14.0`. 

https://github.com/plotly/dash/issues/732

**Comment by danionescu0** [comment]
Closing because dash does not have a true live update
